---

- name: OS Loops Demo
  hosts: all
  become: true

  tasks:

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - git
        - curl
        - wget